export enum PokemonType {
  Bug = 'bug',
  Dark = 'dark',
  Dragon = 'dragon',
  Electric = 'electric',
  Fairy = 'fairy',
  Fighting = 'fighting',
  Fire = 'fire',
  Flying = 'flying',
  Ghost = 'ghost',
  Grass = 'grass',
  Ground = 'ground',
  Ice = 'ice',
  Normal = 'normal',
  Poison = 'poison',
  Psychic = 'psychic',
  Rock = 'rock',
  Steel = 'steel',
  Water = 'water',
}

export const pokemonTypes: PokemonType[] = [
  PokemonType.Bug,
  PokemonType.Dark,
  PokemonType.Dragon,
  PokemonType.Electric,
  PokemonType.Fairy,
  PokemonType.Fighting,
  PokemonType.Fire,
  PokemonType.Flying,
  PokemonType.Ghost,
  PokemonType.Grass,
  PokemonType.Ground,
  PokemonType.Ice,
  PokemonType.Normal,
  PokemonType.Poison,
  PokemonType.Psychic,
  PokemonType.Rock,
  PokemonType.Steel,
  PokemonType.Water,
]
