version: '3.8'
volumes:
  postgresql_data:
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: websitedb
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/var/lib/postgresql/data'

  maildev: # https://github.com/maildev/maildev
    image: maildev/maildev
    ports:
      - '1080:1080'
      - '1025:1025'
