// autogenerated by @pkg/database/src/common/codegen.js
const _moveIds = ['pound'] as const

export type MoveId = (typeof _moveIds)[number]

export function getMoveIds(): readonly MoveId[] {
  return _moveIds
}
