// autogenerated with @pkg/database/lib/codegen/codegen.cjs
export const _moveIds = ['pound'] as const

export type MoveId = (typeof _moveIds)[number]

export function getMoveIds(): readonly MoveId[] {
  return _moveIds
}
