name: 'Check code quality'
description: 'Checks code quality: prettier, linters, build and test'
env:
  VERCEL_ENV: development
runs:
  using: 'composite'
  steps:
    - shell: bash
      name: Run Quality Checks
      run: pnpm quality-checks
