name: 'Check code quality'
description: 'Checks code quality: prettier, linters, build and test'
env:
  VERCEL_ENV: development
runs:
  using: 'composite'
  steps:
    - shell: bash
      name: Generate and build code
      run: |
        pnpm -r codegen
        pnpm build

    - shell: bash
      name: Run prettier checks
      run: pnpm prettier-check

    - shell: bash
      name: Run ESLint
      run: pnpm lint

    - shell: bash
      name: Run tests
      run: pnpm test:ci
