// autogenerated by @pkg/database/src/common/codegen.js
const _abilityIds = ['stench'] as const

export type AbilityId = (typeof _abilityIds)[number]

export function getAbilityIds(): readonly AbilityId[] {
  return _abilityIds
}
