import { MDXFileContent } from '@pkg/mdx/src/types'

export enum EntryType {
  Page = 'Page',
  Article = 'Article',
}

type CommonEntryFields = {
  id: string
  type: EntryType
  title: string
  slug: string
  url: string
  createdAt: string
  updatedAt?: string
  publishedAt?: string
  isDraft?: boolean
  summary?: string
  bannerImageUrl?: string
  videoUrl?: string
  metaTitle: string
  metaDescription: string
  robots?: string
  enableComments?: boolean
  enableSharing?: boolean
  isAutogenerated?: boolean
  category?: string
  tags?: string[]
}

export type ArticleEntry = MDXFileContent<CommonEntryFields>
export type PageEntry = MDXFileContent<CommonEntryFields>
export type Entry = PageEntry | ArticleEntry
