// autogenerated with @pkg/database/lib/codegen/codegen.cjs
export const _pokedexIds = [
  'national',
  'kanto',
  'johto',
  'hoenn',
  'sinnoh',
  'sinnoh-pt',
  'johto-hgss',
  'unova',
  'unova-b2w2',
  'kalos',
  'kalos-central',
  'kalos-coastal',
  'kalos-mountain',
  'hoenn-oras',
  'alola',
  'alola-melemele',
  'alola-akala',
  'alola-ulaula',
  'alola-poni',
  'alola-usum',
  'alola-melemele-usum',
  'alola-akala-usum',
  'alola-ulaula-usum',
  'alola-poni-usum',
  'kanto-lgpe',
  'galar',
  'galar-initial',
  'galar-isle-armor',
  'galar-crown-tundra',
  'hisui',
  'hisui-obsidian',
  'hisui-crimson',
  'hisui-cobalt',
  'hisui-coronet',
  'hisui-alabaster',
  'paldea',
  'paldea-initial',
  'kitakami',
  'blueberry',
] as const

export type PokedexId = (typeof _pokedexIds)[number]

export function getPokedexIds(): readonly PokedexId[] {
  return _pokedexIds
}
