export type MDXDataType = Record<string, unknown>

export type MDXIndex = {
  index: Partial<{
    [key in MDXEntryType]: Array<{
      path: string
      title: string
      slug: string
      createdAt: string
      modifiedAt: string
      isAutogenerated: boolean | undefined
    }>
  }>
  modifiedAt: string
}

export type MDXFileContent<DataType extends Record<string, unknown>> = {
  _source: {
    file: string
    type: string | undefined
  }
  body: string
} & DataType

export enum MDXEntryType {
  Page = 'Page',
  Article = 'Article',
}

export type MDXEntryMetadata = {
  id: string
  type: MDXEntryType
  title: string
  slug: string
  url: string
  createdAt: string
  updatedAt?: string
  publishedAt?: string
  isDraft?: boolean
  summary?: string
  bannerImageUrl?: string
  videoUrl?: string
  metaTitle: string
  metaDescription: string
  robots?: string
  enableComments?: boolean
  enableSharing?: boolean
  isAutogenerated?: boolean
  category?: string
  tags?: string[]
}

export type MDXPage = MDXFileContent<MDXEntryMetadata>
