// autogenerated by @pkg/database/src/common/codegen.js
const _natureIds = [
  'hardy',
  'lonely',
  'adamant',
  'naughty',
  'brave',
  'docile',
  'bold',
  'impish',
  'lax',
  'relaxed',
  'serious',
  'timid',
  'hasty',
  'jolly',
  'naive',
  'bashful',
  'modest',
  'mild',
  'rash',
  'quiet',
  'quirky',
  'calm',
  'gentle',
  'careful',
  'sassy',
] as const

export type NatureId = (typeof _natureIds)[number]

export function getNatureIds(): readonly NatureId[] {
  return _natureIds
}
