const fs = require('node:fs')
const { parseJsonFile } = require('@pkg/utils/lib/commonjs/index.cjs')

function generateIdsTsFileFromData(data, outCodeFile, singularName) {
  const constantValues = Array.from(data.map(item => item.id))
  const capitalizedName = singularName.charAt(0).toUpperCase() + singularName.slice(1)

  const code = `// autogenerated with @pkg/database/lib/codegen/codegen.cjs
export const _${singularName}Ids = ${JSON.stringify(constantValues, undefined, 2)} as const

export type ${capitalizedName}Id = (typeof _${singularName}Ids)[number]

export function get${capitalizedName}Ids(): readonly ${capitalizedName}Id[] {
  return _${singularName}Ids
}
`
  fs.writeFileSync(outCodeFile, code)
}

module.exports = {
  generateIdsTsFile,
}

function generateIdsTsFile(srcDataFile, outCodeFile, singularName) {
  const data = parseJsonFile(srcDataFile)
  generateIdsTsFileFromData(data, outCodeFile, singularName)
}

module.exports = {
  generateIdsTsFileFromData,
  generateIdsTsFile,
}
