name: Update Tokens every 12h

env:
  NODE_VERSION: '>=18.5.0'
  PNPM_VERSION: 8.9

on:
  schedule:
    - cron: '0 3 * * *' # every day at 3am
  workflow_dispatch:

jobs:
  update_tokens:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Configure PATH env var
        run: echo "$PWD/node_modules/.bin" >> $GITHUB_PATH

      - name: Use node_modules cache
        id: node_modules-cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node_modules-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Update Patreon Tokens
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }}
        run: |
          pnpm pkg:patreon run refreshCreatorToken

      - name: Redeploy vercel project
        env:
          VERCEL_DEPLOY_URL: ${{ secrets.VERCEL_DEPLOY_URL }}
        run: |
          curl -s -X POST "${VERCEL_DEPLOY_URL}?buildCache=false"
